#!/bin/bash
[[ ! $AR_DIR ]] && source $HOME/.adryd/constants.sh
source $AR_DIR/constants.sh
source $AR_DIR/lib/log.sh
source $AR_DIR/lib/ensure.sh

export AR_MODULE='vscode'

function check() {
    pacman -Qi code && return 0
    return 1
}

function install() {
    [[ true ]]
}

