#!/usr/bin/env bash
cd "$(dirname "$0")" || exit $?
[[ "${USER}" != "root" ]] && echo "Please run as root" && exit 1

# Lang files
sed -i "s/#en_US-UTF-8 UTF-8/en_US-UTF-8 UTF-8/" /etc/locale.gen &> /dev/null
locale-gen
if ! grep "^LANG=en_US-UTF-8" /etc/locale.conf &> /dev/null; then
 echo "LANG=en_US-UTF-8" >> /etc/locale.conf
fi

# Init keyring
pacman-key --init
pacman-key --populate

# Temporarily add mirrors
lockStr="## adryd-dotfiles-lock (container-init)"
if ! grep "^${lockStr}" /etc/pacman.d/mirrorlist &> /dev/null \
  || ! grep "Arch Linux mirrorlist generated by Reflector" /etc/pacman.d/mirrorlist &> /dev/null; then
  echo "${lockStr}" >> /etc/pacman.d/mirrorlist
  cat ./mirrorlist.txt >> /etc/pacman.d/mirrorlist
fi

# Make pacman go brr
sed -i "s/#ParallelDownloads/ParallelDownloads/" /etc/pacman.conf &> /dev/null

# Update packages
pacman -Syyu --noconfirm

# Install reflector to get an up-to-date mirror list
pacman -S reflector --noconfirm
reflector > /etc/pacman.d/mirrorlist