#!/bin/bash
[[ ! $AR_DIR ]] && source $HOME/.adryd/constants.sh
source $AR_DIR/constants.sh
source $AR_DIR/lib/log.sh
source $AR_DIR/lib/ensure.sh

export AR_MODULE='discord'
discordTmp=$AR_TMP/discord
discordLocal="$HOME/.local/share"
discordBranches=('stable' 'ptb' 'canary' 'development')
discordDownloadEndpoint='https://discord.com/api/download'
discordDownloadOptions='?platform=linux&format=tar.gz'

function check() {
    return 0
}

function install() {
    # Make temp folder
    log 0 'Making work folder'
    mkdir -p $discordTmp/

    # Sanity check, this shouldn't have to happen
    if [[ ! -e $discordLocal ]]; then
        log 3 'Making user programs folder'
        mkdir -p $discordLocal
    fi
    
    # make sure all our dependencies are installed
    ensure curl zlib tar sed

    # discord dependencies
    ensure gtk3 libnotify libxss nspr nss emoji-font noto-fonts-cjk libpulse xdg-utils

    # for every branch
    for discordBranch in "${discordBranches[@]}"; do
        # Discord Naming Fixes
        log 0 'Variable setup'
        if [[ $discordBranch = 'stable' ]]; then
            discordDownloadURL="$discordDownloadEndpoint$discordDownloadOptions"
            discordName='Discord'
            discordNameLowercase='discord'
        elif [[ $discordBranch = 'ptb' ]]; then
            discordDownloadURL="$discordDownloadEndpoint/$discordBranch$discordDownloadOptions"
            # ^^ capitalizes all characters
            discordName="Discord${discordBranch^^}"
            discordNameLowercase="discord-$discordBranch"
        else
            discordDownloadURL="$discordDownloadEndpoint/$discordBranch$discordDownloadOptions"
            # ^ capitalizes first character
            discordName="Discord${discordBranch^}"
            discordNameLowercase="discord-$discordBranch"
        fi
        
        if [[ ! -e $discordTmp/$discordName.tar.gz ]]; then
            log 3 "Downloading $discordBranch"
            curl -fsSL $discordDownloadURL -o $discordTmp/$discordName.tar.gz
        else
            log 1 "Download skipped for $discordBranch"
        fi

        if [[ ! -e $discordTmp/$discordName.tar.gz ]]; then
            log 5 "Download failed for $discordBranch"
            continue
        fi

        # Overwrite existing installs
        if [[ -e $discordLocal/$discordName ]]; then
            log 3 "Deleting existing $discordBranch install"
            rm -rf $discordLocal/$discordName
        fi

        # Extract to $discordLocal
        log 3 "Extracting $discordBranch"
        tar -xf $discordTmp/$discordName.tar.gz -C $discordLocal

        log 2 "Installing $discordBranch"
        # If no local icon folder exists, make one
        if [[ ! -e $discordLocal/icons/hicolor/256x256 ]]; then
            log 1 "Making icon folder."
            mkdir -p $discordLocal/icons/hicolor/256x256
        fi

        # Check to make sure no existing icons exist
        if [[ -e $discordLocal/icons/hicolor/256x256/$discordNameLowercase.png ]]; then
            log 1 "Deleting existing $discordBranch icon"
            rm -rf $discordLocal/icons/hicolor/256x256/$discordNameLowercase.png
        fi

        log 1 "Linking $discordBranch icon"
        ln -s $discordLocal/$discordName/discord.png $discordLocal/icons/hicolor/256x256/$discordNameLowercase.png

        # Fix executable location, StartupWMClass and icon
        log 1 "Fixing $discordBranch desktop file"
        sed -i "s/Exec=\/usr\/share\/$discordNameLowercase\/$discordName/Exec=\"\/home\/$USER\/.local\/share\/$discordName\/$discordName\"/" \
            $discordLocal/$discordName/$discordNameLowercase.desktop
        # This doesn't seem to do anything unfortunately :(
        sed -i "s/StartupWMClass=discord/StartupWMClass=$discordName/" \
            $discordLocal/$discordName/$discordNameLowercase.desktop
        sed -i "s/Icon=$discordNameLowercase/Icon=\/home\/$USER\/.local\/share\/icons\/hicolor\/256x256\/$discordNameLowercase.png/" \
            $discordLocal/$discordName/$discordNameLowercase.desktop

        # Delete existing .desktop files
        if [[ -e $discordLocal/applications/$discordNameLowercase.desktop ]]; then
            log 1 "Deleting existing $discordBranch desktop file"
            rm -rf $discordLocal/applications/$discordNameLowercase.desktop
        fi

        # Symlink new .desktop files
        log 1 "Copying $discordBranch desktop file"
        cp $discordLocal/$discordName/$discordNameLowercase.desktop $discordLocal/applications/$discordNameLowercase.desktop

        # Run discord postinst script
        # it errors cause of bad code :)
        log 3 "Running Discord's postinstall script for $discordBranch"
        $discordLocal/$discordName/postinst.sh &> /dev/null
    done
}
